import { defineConfig } from "vitest/config";
import path from "node:path";

export default defineConfig({
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "apps/web"),
      "next-auth/providers/discord": path.resolve(__dirname, "src/tests/stubs/next-auth-discord.ts"),
      "next/headers": path.resolve(__dirname, "src/tests/stubs/next-headers.ts"),
      "next/link": path.resolve(__dirname, "src/tests/stubs/next-link.ts"),
      "next/server": path.resolve(__dirname, "src/tests/stubs/next-server.ts"),
      "lucide-react": path.resolve(__dirname, "src/tests/stubs/lucide-react.ts"),
    },
  },
  test: {
    environment: "node",
    setupFiles: ["src/tests/setup.ts"],
    include: [
      "src/tests/test-campaign-db-isolation.ts",
      "src/tests/test-campaign-fallback-log-dedupe.ts",
      "src/tests/test-campaign-scope-foundations.ts",
      "src/tests/test-guild-mapping-auto-create.ts",
      "src/tests/test-db-bootstrap-legacy-index-compat.ts",
      "src/tests/test-stopline-no-getdb-runtime.ts",
      "src/tests/test-stopline-active-session-boundary.ts",
      "src/tests/test-stopline-recap-service-boundary.ts",
      "src/tests/test-stopline-runtime-scope-fallbacks.ts",
      "src/tests/test-stopline-observability-runtime.ts",
      "src/tests/test-runtime-scope-helpers.ts",
      "src/tests/test-voice-playback-controller.ts",
      "src/tests/test-transcript-system-isolation.ts",
      "src/tests/test-transcript-bronze-view-contract.ts",
      "src/tests/test-silver-seq-determinism.ts",
      "src/tests/test-silver-seq-metrics-contract.ts",
      "src/tests/test-eligibility-mask-parity-c2e20.ts",
      "src/tests/test-megameecap-dry-run-determinism.ts",
      "src/tests/test-megameecap-context-bounds.ts",
      "src/tests/megameecap/segmenter.test.ts",
      "src/tests/megameecap/contextCarry.test.ts",
      "src/tests/megameecap/prompts.segment.test.ts",
      "src/tests/megameecap/prompts.final.test.ts",
      "src/tests/megameecap/orchestrator.test.ts",
      "src/tests/megameecap/io.test.ts",
      "src/tests/registry/test-scan-names.ts",
      "src/tests/registry/test-review-names.ts",
      "src/tests/smoke/test-megameecap-fixture.ts",
      "src/tests/smoke/test-silver-seq-fixture.ts",
      "src/tests/voice/test-voice-interrupt.ts",
      "src/tests/test-receiver-stop-phrase-bypass.ts",
      "src/tests/test-receiver-gating.ts",
      "src/tests/test-receiver-rejected-path.ts",
      "src/tests/test-meepo-wake-ambient.ts",
      "apps/web/lib/starstory/__tests__/reducer.test.ts",
      "apps/web/lib/starstory/__tests__/replay.test.ts",
      "apps/web/lib/starstory/__tests__/engine.test.ts",
      "apps/web/lib/starstory/__tests__/visualProjector.test.ts",
      "apps/web/lib/starstory/__tests__/discordInstallAdapter.test.ts",
      "apps/web/lib/starstory/__tests__/transcriptAdapter.test.ts",
      "apps/web/lib/starstory/__tests__/validationAdapter.test.ts",
      "apps/web/lib/__tests__/canonicalOrigin.test.ts",
      "apps/web/lib/__tests__/canonicalMiddleware.test.ts",
      "apps/web/lib/__tests__/authOriginGuard.test.ts",
      "src/tests/test-meepo-wake-response-gating.ts",
      "src/tests/test-meepo-auto-sleep.ts",
      "src/tests/test-showtime-lifecycle-authority.ts",
      "src/tests/test-meepo-awaken-ordering.ts",
      "src/tests/test-meepo-showtime-end-leaves-voice.ts",
      "src/tests/test-meepo-legacy-session-persistence.ts",
      "src/tests/test-meepo-awaken-component-gating.ts",
      "src/tests/test-awaken-continue-custom-id.ts",
      "src/tests/test-meepo-settings-awaken-params.ts",
      "src/tests/test-sessions-view-transcript-auto-cache.ts",
      "src/tests/test-meepo-sessions-recap-contract.ts",
      "src/tests/test-meepo-voice-boundary.ts",
      "src/tests/test-voice-reply-degradation-contract.ts",
      "src/tests/test-meta-meepo-voice-contract.ts",
      "src/tests/test-text-reply-policy.ts",
      "src/tests/test-persona-canon-mode-switch.ts",
      "src/tests/test-recap-engine.ts",
      "src/tests/test-artifact-naming-fallback.ts",
      "src/tests/test-recall-safety.ts",
      "src/tests/smoke/test-meepo-golden-path-v11.ts",
      "src/tests/test-speaker-label.ts",
      "src/tests/test-receiver-canon-dm-firewall.ts",
      "src/tests/test-stt-prompt-refresh.ts",
      "src/tests/test-stt-openai-prompt-forwarding.ts",
      "src/tests/test-prompts-canon-rail.ts",
      "src/tests/test-retrieval-dedupe.ts",
      "src/tests/test-no-direct-meepomind-access.ts",
      "src/tests/test-prompt-bundle-includes-retrieval.ts",
      "src/tests/test-retrieval-fallback.ts",
      "src/tests/test-always-tier.ts",
      "src/tests/test-meepo-context-heartbeat.ts",
      "src/tests/test-meepo-context-snapshot.ts",
      "src/tests/test-meepo-context-actions.ts",
      "src/tests/test-observability-short-session.ts",
      "src/tests/test-user-facing-error-formatter.ts",
      "src/tests/test-meepo-context-mini-first.ts",
      "src/tests/test-meepo-context-worker.ts",
      "src/tests/test-session-status-invariants.ts",
      "src/tests/test-session-boot-reconcile.ts",
      "src/tests/test-session-recovery.ts",
      "src/tests/test-session-speaker-attribution.ts",
      "src/tests/test-session-recaps-api.ts",
      "src/tests/test-recap-service-contract.ts",
      "src/tests/test-web-auth-context-guard.ts",
      "src/tests/test-web-active-campaign-resolver.ts",
      "src/tests/test-web-session-scope-disambiguation.ts",
      "src/tests/test-web-dashboard-phaseb.ts",
      "src/tests/test-web-recap-visibility.ts",
      "src/tests/test-web-phase55-authority-and-recaps.ts",
      "src/tests/test-web-compendium-dm-permissions.ts",
      "src/tests/test-web-compendium-pc-discord-user-validation.ts",
      "src/tests/test-web-compendium-pc-discord-user-hardening.tsx",
      "src/tests/test-web-landing-constellation.ts",
      "src/tests/test-web-discord-guild-cache-policy.ts",
      "src/tests/test-web-scope-guards.ts",
      "src/tests/test-guild-seen-discord-users.ts",
      "src/tests/test-provider-config-foundations.ts",
      "src/tests/test-provider-adapters.ts",
      "src/tests/test-web-provider-settings.ts",
      "src/tests/test-web-rename-routes.ts",
      "src/tests/test-elevated-access.ts",
      "src/tests/test-lab-session-resolve.ts",
      "src/tests/test-lab-autocomplete-routing.ts",
      "src/tests/test-lab-wake.ts",
      "src/tests/test-lab-awaken-reset.ts",
      "src/tests/test-lab-gating-contract.ts",
      "src/tests/commands/test-command-manifests-phase1a.ts",
      "src/tests/commands/test-lab-gating.ts",
      "src/ledger/__tests__/awakeningStateRepo.test.ts",
      "src/awakening/__tests__/AwakenEngine.test.ts",
      "src/awakening/__tests__/choicePrompt.test.ts",
      "src/awakening/__tests__/roleSelectPrompt.test.ts",
      "src/awakening/__tests__/registryBuilderPromptResume.test.ts",
      "src/awakening/__tests__/commitActions.test.ts",
      "src/awakening/__tests__/awakenEngineCommitFlow.test.ts",
      "src/scripts/awakening/__tests__/loader.test.ts",
      "src/meepoMind/__tests__/dmNameRoundTrip.test.ts",
      "src/tools/heartbeat/replay.test.ts",
    ],
    sequence: {
      concurrent: false,
    },
    testTimeout: 30000,
  },
});
