param(
  [string]$Root = ".",
  [string]$Out = "docs/REPO_SKELETON.md"
)

$excludeDirs = @("node_modules", "out", "runs", "data", ".git", ".next", ".turbo", "dist", "build", "coverage")
$resolvedRoot = (Resolve-Path $Root).Path

$files = Get-ChildItem -Path $resolvedRoot -Recurse -File | Where-Object {
  $rel = $_.FullName.Replace($resolvedRoot, "").TrimStart("\")
  $segments = $rel -split "[\\/]"
  -not (($segments | Where-Object { $excludeDirs -contains $_ }).Count -gt 0)
} | Sort-Object FullName

Set-Content -Path $Out -Encoding UTF8 -Value "# Repo Skeleton (autogenerated)"
Add-Content -Path $Out -Encoding UTF8 -Value ""
Add-Content -Path $Out -Encoding UTF8 -Value "Generated by tools/write-repo-skeleton.ps1."
Add-Content -Path $Out -Encoding UTF8 -Value ""
Add-Content -Path $Out -Encoding UTF8 -Value '```text'
foreach ($f in $files) {
  $rel = $f.FullName.Replace($resolvedRoot, "").TrimStart("\")
  Add-Content -Path $Out -Encoding UTF8 -Value $rel
}
Add-Content -Path $Out -Encoding UTF8 -Value '```'

Write-Host ("Wrote " + $Out)
